### ISSUE TITLE
Grandthrax Review

### ISSUE THREAD

**Issue by Grandthrax** [GalloDaSballo/wbtc-levered-strat#1]
https://github.com/GalloDaSballo/wbtc-levered-strat/blob/master/contracts/Strategy.sol#L74

These numbers should be much higher. Particularly profitFactor and debtThreshold. We can discuss exact numbers on deployment.

-----------
https://github.com/GalloDaSballo/wbtc-levered-strat/blob/master/contracts/Strategy.sol#L95

This is fine but is a style choice and worth considering. Personally I prefer estimatedTotalAssets to include pending rewards. Without this then profitFactor won't work in harvestTrigger.

----------
https://github.com/GalloDaSballo/wbtc-levered-strat/blob/master/contracts/Strategy.sol#L114

You withdraw everything each time you need to withdraw anything?! Why? What happens if we can't withdraw in one go?

---------------
https://github.com/GalloDaSballo/wbtc-levered-strat/blob/master/contracts/Strategy.sol#L458

I really don't like unbounded loops like this. if we end up with dust it will never end and the tx will revert. And if we cant withdraw in one go then it will never end. Also by limiting yourself to having to be able to withdraw all in one shot you can't get close to the max collateral factor.

---------
https://github.com/GalloDaSballo/wbtc-levered-strat/blob/master/contracts/Strategy.sol#L177

not needed inside current if/else

----------
https://github.com/GalloDaSballo/wbtc-levered-strat/blob/master/contracts/Strategy.sol#L230

considering we are looking for 1-1 swaps we should be able to set a minOut here. I'd check for what the output amount is and then only do if it above our threshold. Something like rewardsAmount*maxDiscount/MAX_BPS. where maxDiscount is what percent discount on 1-1 we are willing to take. settable by gov.

I'd also move the sell staave to aave part to another function and allow it to be callable by onlyKeepers. So if we build up too big a balance of staave we can sell it in parts. Therefore either sell all during harvest or drip out using manual function

----------
https://github.com/GalloDaSballo/wbtc-levered-strat/blob/master/contracts/Strategy.sol#L67

Does this mean 30% away from liquidation? That sounds like a lot. Let's talk about how close we should get to liquidation. With AAVE there is different max LTV and liquidation threshold so it means we can get pretty close to max ltv.

------------
https://github.com/GalloDaSballo/wbtc-levered-strat/blob/master/contracts/Strategy.sol#L415

I don't really understand this part. The max value doesn't take into account minHealth

---------
https://github.com/GalloDaSballo/wbtc-levered-strat/blob/master/contracts/Strategy.sol#L432

The invest loop always runs 5 times. why? won't this take us to under minHealth and then we need to deleverage in debtBelowHealth?

--------
https://github.com/GalloDaSballo/wbtc-levered-strat/blob/master/contracts/Strategy.sol#L299

I suggest a backup migrate incase one of these functions break. Currently if _divestFromAAVE() breaks you are trapped as every function that returns money uses it.

**Comment by GalloDaSballo** [comment]
Addresses in follow up Commits

**Comment by GalloDaSballo** [comment]
Addressed in follow up commits
