### ISSUE TITLE
jmonteer review

### ISSUE THREAD

**Issue by jmonteer** [GalloDaSballo/wbtc-levered-strat#2]

**Comment by jmonteer** [comment]
https://github.com/GalloDaSballo/wbtc-levered-strat/blob/37ee499088bca2d6945e7f4cdecc167344fca272/contracts/Strategy.sol#L138

loss should be 0 at the beginning so it is not needed to add new loss

**Comment by jmonteer** [comment]
as a suggestion:

I would add the possibility to claim rewards passing through the unstaking (cooldown) period, just in case the liquidity pool dries out and we can't go from stkAAVE to AAVE that easy.

maybe add a switch to be able to choose between both alternatives (swap or unstake)

**Comment by jmonteer** [comment]
https://github.com/GalloDaSballo/wbtc-levered-strat/blob/37ee499088bca2d6945e7f4cdecc167344fca272/contracts/Strategy.sol#L35-L52

as per Aave docs, it is better to request addresses from the Addresses Provider

![image](https://user-images.githubusercontent.com/68742302/127136415-df5acc4c-dff3-412b-aa0f-adcb29e7f7de.png)

https://docs.aave.com/developers/the-core-protocol/addresses-provider

EDIT: also this would make it easier to make this strat for a generic want (retrieving aToken / vdToken from Addresses Provider)

**Comment by jmonteer** [comment]
IMO, we should be able to divest partially

https://github.com/GalloDaSballo/wbtc-levered-strat/blob/37ee499088bca2d6945e7f4cdecc167344fca272/contracts/Strategy.sol#L129

vault may request part of the funds and this basically means that each harvest that makes the strategy return some funds to the vault requires another harvest to lever back up

**Comment by jmonteer** [comment]
this is scary:

https://github.com/GalloDaSballo/wbtc-levered-strat/blob/37ee499088bca2d6945e7f4cdecc167344fca272/contracts/Strategy.sol#L521

maybe to make it less scary we can add a backstop which is set manually and if the number of iterations reaches that point, it stops. this could make sense in case the deleverage requires more iterations than a single transaction can fit. 

in this case, manually doing the first deleveraging iterations should solve it, though.

**Comment by jmonteer** [comment]
idea:

taking into account that we can withdraw up to the liquidation threshold (instead of LTV) we can actually borrow up to the liquidation threshold (75% in this case).

in this case, considering this is not subject to price movements, I think it may make sense to go to 73-74% instead of staying at 70%, with the boost in APY that that means. 

this will require to use flash loans to lever up, though. Flash loans would also solve the while loop for deleverage, so worth considering.

**Comment by GalloDaSballo** [comment]
Also see: https://github.com/GalloDaSballo/wbtc-levered-strat/commit/1e0437c215b044cfe94a1c2897392c8d49a1353e
For fixes on redeeming stkAAVe

**Comment by GalloDaSballo** [comment]
Addressed in follow up commits
